import type { CloudSettings } from './types';

export const DEFAULTS: CloudSettings = {
  col: '#b9c4d9',
  dens: 1,
  grid: 1,
  lockGrid: true,
  fuzzy: 4,
  rand: 6,
  inset: 7,
  angX: 0.40,
  angY: 0.34,
  angR: 0.80,
  shX: 0,
  shY: -26,
  shSize: 12,
  shOp: 0.5,
  shCol: '#7c89a3',
  hiX: -8,
  hiY: 24,
  hiSize: 12,
  hiOp: 0.6,
  hiCol: '#ffffff',
  scale: 1,
  rotate: 0,
  flipX: false,
  flipY: false,
  opacity: 1,
};
